version: '3.8'
services:
  db:
    image: phidata/pgvector:16
    container_name: pgvector
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5532:5432"
    volumes:
      - pgvolume:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://ai:ai@db:5432/ai
    volumes:
      - .:/app
    command: streamlit run autorag.py --server.port=8000 --server.address=0.0.0.0

volumes:
  pgvolume:
